apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # ---------------------------------
  # จาก environment: ของ postgres_new
  # ---------------------------------
  POSTGRES_DB: "user-db"
  POSTGRES_USER: "newuser"
  POSTGRES_PASSWORD: "newpassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
stringData:
  # ---------------------------------
  # จาก environment: ของ pgadmin_new
  # ---------------------------------
  PGADMIN_DEFAULT_EMAIL: "admin2@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "admin2"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  DATABASE_DSN: "mongodb+srv://wutthichod:tonkla4543@cluster0.e4yp1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
